language: cpp

addons:
  apt:
    packages: libboost-all-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9', 'g++-4.9', 'libboost-all-dev']
      env:
        - COMPILER_CC=gcc-4.9
        - COMPILER_CXX=g++-4.9

install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then tools/travis-cmake.sh; export PATH="$HOME/local/bin:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install cmake boost || brew upgrade cmake boost; fi

cache:
    directories:
      - $HOME/local

script:
  - mkdir build
  - cd build
  - CXX=$COMPILER_CXX CC=$COMPILER_CC cmake ..
  - make -j$(nproc)
