language: cpp
sudo: false

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.8
            - g++-4.9
            - g++-5
            - g++-6
            - gcc-4.9
            - gcc-5
            - gcc-6
            - python3

cache:
    directories:
        - cmake-3.5.2

compiler:
  - g++-4.9
  - g++-5
  - g++-6
  - clang++-3.8

install:
    - tools/travis-cmake.sh
    - export PATH=$PWD/cmake-3.5.2/dist/bin:$PATH

script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
