language: cpp
sudo: required
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get install software-properties-common
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x
    - sudo apt-get update
install:
    - sudo apt-get upgrade
script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
    - ctest
