language: cpp
sudo: false
compiler:
    # - gcc
    - clang
install:
    - tools/travis-cmake.sh
    - export PATH=$PWD/cmake-3.4.1/dist/bin:$PATH
script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
    - ctest
cache:
    directories:
        - cmake-3.4.1
