language: cpp
sudo: false

addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5

cache:
    directories:
        - cmake-3.5.2

compiler:
    - gcc
    - clang

install:
    - if [ "$CXX" == "g++" ]; then export CXX=g++-5; export CC=gcc-5; fi
    - if [ "$CXX" == "clang++" ]; then export CXX=clang++-3.7; export CC=clang-3.7; fi
    - tools/travis-cmake.sh
    - export PATH=$PWD/cmake-3.5.2/dist/bin:$PATH

script:
    - cmake --version
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
