language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - COMPILER_CC=gcc-5
        - COMPILER_CXX=g++-5

cache: pip

install:
  - pip install conan
  - conan install

script:
  - mkdir build && cd build
  - CXX=$COMPILER_CXX CC=$COMPILER_CC cmake -DCMAKE_BUILD_TYPE=Quick ..
  - make -j$(nproc)
