language: cpp

matrix:
  include:
    - env: GCC_VERSION=5
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5

cache: pip

before_install:
  - mkdir build && cd build
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}" CONAN_COMPILER="gcc" CONAN_COMPILER_VERSION="5.4"; fi
  - which $CXX
  - which $CC
  - echo "$CONAN_COMPILER $CONAN_COMPILER_VERSION"
  - $CXX --version

install:
  - pip install --user conan
  - conan install ..

script:
  - export OMP_NUM_THREADS=4
  - cmake -DCMAKE_BUILD_TYPE=Quick ..
  - make -j$(nproc)
