language: cpp

matrix:
  include:
    - env: GCC_VERSION=5
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
    - env: GCC_VERSION=6
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6

cache: pip

before_install:
  - mkdir build && cd build
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - which $CXX
  - which $CC
  - $CXX --version

install:
  - pip install --user conan
  - conan install ..

script:
  - export OMP_NUM_THREADS=4
  - CXX=$COMPILER_CXX CC=$COMPILER_CC cmake -DCMAKE_BUILD_TYPE=Quick ..
  - make -j$(nproc)
